# Generated by Django 4.0.1 on 2022-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reacttest',
            old_name='objective',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='reacttest',
            old_name='reactname',
            new_name='title',
        ),
        migrations.AddField(
            model_name='reacttest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
