# Generated by Django 4.0.1 on 2022-02-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0002_rename_objective_reacttest_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReactTest',
            new_name='ToDo',
        ),
    ]
